---
title: 'Potential Eureka'
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-architect
description:
- software engineering and programming stuff
author:
- Ferit Tunçer
plugins:
- jekyll-sitemap
- jekyll-seo-tag
